[network]
name = "devnet"
boot_contracts = ["poc-consensus", "bns", "costs-v2", "costs-3", "costs", "signers", "pox", "pox-2", "pox-3", "pox-4", "lockup"]
pooled_stacking = false

[accounts.deployer]
mnemonic = "female adjust gallery certain visit token during great side clown fitness like hurt clip knife warm bench start reunion globe detail dream depend fortune"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "shadow private easily thought say logic fault paddle word top book during ignore notable orange flight clock image wealth health outside kitten belt reform"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "board list obtain sugar hour worth raven scout denial thunder horse logic fury scorpion fold genuine phrase wealth news aim below celery when cabin"
balance = 100_000_000_000_000
