[network]
name = "devnet"
boot_contracts = ["poc-consensus", "bns", "costs-v2", "costs-3", "costs", "signers", "pox", "pox-2", "pox-3", "pox-4", "lockup"]
pooled_stacking = false

[accounts.deployer]
mnemonic = "fetch outside black test wash cover just alter gag judge pillar crime"
balance = 100_000_000_000_000

[accounts.wallet_1]
mnemonic = "spoil sock coyote verify alert coin garden dream pattern coast bargain grunt"
balance = 100_000_000_000_000

[accounts.wallet_2]
mnemonic = "arrange scale orient half ugly kid tick polar goddess fortune circle brick"
balance = 100_000_000_000_000
